// flow-typed signature: 6030ba5531ddfe51985d88b1e48dbaf7
// flow-typed version: <<STUB>>/apollo-link-batch-http_v^1.2.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-batch-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-batch-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-batch-http/lib/batchHttpLink' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-batch-http/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-batch-http/lib/batchHttpLink.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/batchHttpLink'>;
}
declare module 'apollo-link-batch-http/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/bundle.umd'>;
}
declare module 'apollo-link-batch-http/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-batch-http/lib/index'>;
}
