// flow-typed signature: ee3757e4fe1d11a9dbc8bfdb1a3021f4
// flow-typed version: <<STUB>>/postcss-nesting_v^7.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nesting'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nesting' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-nesting/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-nesting/index.cjs.js' {
  declare module.exports: $Exports<'postcss-nesting/index.cjs'>;
}
