// flow-typed signature: 9969f62c5c8fc1f78b229cb66334a5b4
// flow-typed version: <<STUB>>/postcss-selector-matches_v^4.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-selector-matches'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-selector-matches' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-selector-matches/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-selector-matches/dist/replaceRuleSelector' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-selector-matches/dist/index.js' {
  declare module.exports: $Exports<'postcss-selector-matches/dist/index'>;
}
declare module 'postcss-selector-matches/dist/replaceRuleSelector.js' {
  declare module.exports: $Exports<
    'postcss-selector-matches/dist/replaceRuleSelector',
  >;
}
